print("hello world")
#help for ubuntu desk
# nOHAEOFBEWOUBF
# AEJNFAEOPIHFOAIHFAO
# AJNFAOIBFAOIBA

""""LDFGDGGDDBGUBGFIUDGIUDFG
FGDGNDOOFGBIUBFDSIGDF
DFIIHHBUHFDHGUOIZHB[UGH[ZDGDG
FGUBIBFPGIHBBIDGZFDZG
FGIUIPUPIGBIUDGRBUOBZGNDFS
DFGIOHH[GGDP]]]"""


# heloo sqeniei
# KJNXIUDFNXZIU

